### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by chunkypixel** [tebl/Composite-Video-Amplifier#1]
Hi,
I found your board on PCBWay at the start of the year and have just installed it into my Vadar 2600 today.  Just wanted to say thank you for a great board - really happy with the results 👍 
![board](https://user-images.githubusercontent.com/20292815/82114438-23d5d800-97a0-11ea-944a-aa5435e1b661.png)
I have a spare 7800 which I might put one into down the track also. My current 7800 has a UAV I put in recently but the 2600 side is extremely dark.

**Comment by tebl** [comment]
I'm glad you liked it, It is fun seeing it find some use!
